name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo Hello, world!
    - name: Run a multi-line csript
      run:
        echo Add other actions to build,
        echo test, and deploy your project.
